version: '3.8'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super_duper_password
      MYSQL_DATABASE: immo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: